--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagementapi
spec:
  minReadySeconds: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: customermanagementapi
  template:
    metadata:
      labels: 
        app: customermanagementapi
        version: v1.0
    spec:
      containers:
        - name: customermanagementapi
          image: panky7700/customermanagementapi:1.0
          ports:
            - containerPort: 5100
              protocol: "TCP"
          # resources:
          #   limits:
          #     cpu: 1000m
          #     memory: 350Mi              
--- 
apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi
spec: 
  #type: NodePort
  selector:
    app: customermanagementapi
  ports:
    - port: 5100
      targetPort: 5100
      protocol: TCP
      #nodePort: 30005
          

