apiVersion: v1
kind: ConfigMap
metadata: 
  name: rabbitmq-configmap
data:
  rabbitmq.conf: |
    default_user = rabbitmquser
    default_pass = DEBmbwkSrzy9D1T9cJfa
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  minReadySeconds: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels: 
        app: rabbitmq
        version: v1.0
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/pitstop/rabbitmq.conf
          ports:
            - containerPort: 5672
              protocol: "TCP"
            - containerPort: 15672
              protocol: "TCP"
          volumeMounts:
            - name: rabbitmq-vol
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/pitstop
      volumes: 
        - name: rabbitmq-vol
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-configmap        
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec: 
  selector:
    app: rabbitmq
  ports:
    - name: test1
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: test2
      port: 15672
      targetPort: 15672
      protocol: TCP        

