---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pit-sqlserver-configmap
data:  
    ACCEPT_EULA: "1"
    MSSQL_PID: Developer
    SA_PASSWORD: 8jkGh47hnDw89Haq8LN2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv-volume-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  
  hostPath:
    path: "/var/mssql-data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pit-sqlserver-pvc-2
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  volumeName: sqlserver-pv-volume-2  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pit-sqlserver-app
  name: pit-sqlserver-deploy
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: pit-sqlserver-pod
  template:
    metadata:
      labels:
        app: pit-sqlserver-pod
    spec:
      containers:
      - name: pit-sqlserver-con
        image: mcr.microsoft.com/azure-sql-edge:latest
        volumeMounts:
          - name: pit-sqlserver-data
            mountPath: /var/opt/mssql
        env:
          - name: ACCEPT_EULA
            valueFrom:
              configMapKeyRef:
                name: pit-sqlserver-configmap
                key: ACCEPT_EULA
          - name: MSSQL_PID
            valueFrom:
              configMapKeyRef:
                name: pit-sqlserver-configmap
                key: MSSQL_PID
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: pit-sqlserver-configmap
                key: SA_PASSWORD                                
        ports:
        - containerPort: 1433
      volumes:
        - name: pit-sqlserver-data
          persistentVolumeClaim:
            claimName: pit-sqlserver-pvc-2

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  selector:
    app: pit-sqlserver-pod
  type: NodePort
  ports:
  - name: admin-sql-view
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 30002